from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(slots=True)
class CatalogFact:
    fact_type: str
    confidence: str
    excerpt: str
    notes: list[str] = field(default_factory=list)


@dataclass(slots=True)
class CatalogEntry:
    candidate_id: str
    name: str
    candidate_type: str
    repository_url: str
    homepage_url: str
    repository_last_pushed_at: str | None
    repository_stars: int | None
    repository_forks: int | None
    repository_open_issues: int | None
    latest_release_published_at: str | None
    releases_last_180d: int | None
    summary: str
    problem_solved: str
    value_hypothesis: str
    baggage_signals: list[str]
    adoption_target_hint: str
    usefulness_level_hint: str
    capability_gap_hint: str
    keywords: list[str]
    facts: list[CatalogFact]
    score_hint: dict[str, int]
    score_rationale: list[str]
    avoid_copying: list[str]
    rejection_reason: str = ""
    reconsider_if: str = "Re-open if future mission changes reduce the baggage concerns."


REFERENCE_CATALOG: list[CatalogEntry] = [
    CatalogEntry(
        candidate_id="open-deep-research",
        name="Open Deep Research",
        candidate_type="framework",
        repository_url="https://github.com/langchain-ai/open_deep_research",
        homepage_url="https://github.com/langchain-ai/open_deep_research",
        repository_last_pushed_at="2026-03-29T00:00:00+00:00",
        repository_stars=6500,
        repository_forks=850,
        repository_open_issues=120,
        latest_release_published_at="2026-03-18T00:00:00+00:00",
        releases_last_180d=6,
        summary="Composable research workflow framework with explicit phase separation and provider seams.",
        problem_solved="Breaks deep research into typed phases instead of collapsing everything into an answer loop.",
        value_hypothesis="Best conceptual base for Research Engine because its orchestration boundaries map cleanly to planning, discovery, compression, and reporting.",
        baggage_signals=["LangGraph-flavored orchestration assumptions", "Report-centric end shape"],
        adoption_target_hint="discovery",
        usefulness_level_hint="structural",
        capability_gap_hint="Need reusable phase boundaries and provider seams for bounded research runs.",
        keywords=["deep research", "workflow", "orchestration", "provider abstraction", "mcp", "typed state"],
        facts=[
            CatalogFact("architecture", "high", "Uses explicit supervisor and researcher phase boundaries with typed run state."),
            CatalogFact("workflow", "high", "Separates search tools from orchestration so discovery providers can be swapped without rewriting the run loop."),
            CatalogFact("integration", "medium", "Its decomposition is a clean fit for a Discovery-side subsystem that must emit inspectable artifacts."),
            CatalogFact("dependency", "medium", "Carries framework assumptions that should be treated as optional, not mandatory, in Research Engine V1."),
        ],
        score_hint={
            "mission_fit": 18,
            "evidence_density": 14,
            "implementation_leverage": 15,
            "self_hostability": 9,
            "composability": 12,
            "maintenance_health": 8,
            "baggage_penalty": -4,
            "adoption_clarity": 9,
        },
        score_rationale=[
            "Best reusable phase decomposition in the source pool.",
            "Clear seams for future DW Discovery integration.",
            "Needs simplification to avoid framework lock-in.",
        ],
        avoid_copying=[
            "Do not inherit LangGraph as a mandatory runtime.",
            "Do not inherit report-first product assumptions.",
        ],
    ),
    CatalogEntry(
        candidate_id="gpt-researcher",
        name="GPT Researcher",
        candidate_type="system",
        repository_url="https://github.com/assafelovic/gpt-researcher",
        homepage_url="https://github.com/assafelovic/gpt-researcher",
        repository_last_pushed_at="2026-03-26T00:00:00+00:00",
        repository_stars=21000,
        repository_forks=2400,
        repository_open_issues=310,
        latest_release_published_at="2026-03-20T00:00:00+00:00",
        releases_last_180d=5,
        summary="Mature deep-research system with strong source collection and cited report generation patterns.",
        problem_solved="Provides a strong collect-curate-synthesize loop across multiple sources and search tools.",
        value_hypothesis="Best donor for deep evidence assembly patterns and source curation heuristics.",
        baggage_signals=["Large feature surface", "Provider sprawl", "Prompt-heavy behavior"],
        adoption_target_hint="discovery",
        usefulness_level_hint="direct",
        capability_gap_hint="Need deeper evidence assembly than shallow search wrappers provide.",
        keywords=["deep research", "retriever", "scraper", "report generation", "multi-source", "cited synthesis"],
        facts=[
            CatalogFact("workflow", "high", "Separates retriever and scraper responsibilities so acquisition can improve without changing synthesis."),
            CatalogFact("architecture", "medium", "Core loop focuses on collecting and curating sources before producing prose."),
            CatalogFact("dependency", "medium", "Adoption cost is higher because the system carries many providers and product modes."),
            CatalogFact("signal", "medium", "Useful as a donor for deep research tactics, not as a direct base."),
        ],
        score_hint={
            "mission_fit": 17,
            "evidence_density": 14,
            "implementation_leverage": 13,
            "self_hostability": 8,
            "composability": 10,
            "maintenance_health": 7,
            "baggage_penalty": -5,
            "adoption_clarity": 8,
        },
        score_rationale=[
            "Strongest evidence-assembly workflow in the pool.",
            "Too broad to inherit wholesale.",
            "Useful pattern donor for curation and acquisition boundaries.",
        ],
        avoid_copying=[
            "Do not inherit the full provider matrix.",
            "Do not inherit memory or vector-store complexity into V1.",
        ],
    ),
    CatalogEntry(
        candidate_id="storm",
        name="STORM / Co-STORM",
        candidate_type="system",
        repository_url="https://github.com/stanford-oval/storm",
        homepage_url="https://github.com/stanford-oval/storm",
        repository_last_pushed_at="2026-03-28T00:00:00+00:00",
        repository_stars=24000,
        repository_forks=2100,
        repository_open_issues=75,
        latest_release_published_at="2026-03-12T00:00:00+00:00",
        releases_last_180d=4,
        summary="Research and cited-report system that separates pre-writing knowledge curation from final writing.",
        problem_solved="Makes acquisition-vs-synthesis boundaries explicit through staged research, outline generation, and cited writing.",
        value_hypothesis="Useful source-intelligence signal for inspectable curation workflow and collaborative evidence gathering.",
        baggage_signals=["Long-form report bias", "Article-generation framing"],
        adoption_target_hint="discovery",
        usefulness_level_hint="structural",
        capability_gap_hint="Need explicit acquisition-vs-synthesis separation and inspectable curation stages.",
        keywords=["research", "citation", "workflow", "curation", "outline", "knowledge", "report generation"],
        facts=[
            CatalogFact("workflow", "high", "Separates pre-writing research and outline generation from final cited writing."),
            CatalogFact("architecture", "medium", "Exposes module seams for retrieval, curation, and report generation."),
            CatalogFact("signal", "medium", "Co-STORM adds collaborative discourse and user steering instead of a single-shot summary flow."),
            CatalogFact("dependency", "medium", "Still relies on external retrieval quality and carries article-generation assumptions."),
        ],
        score_hint={
            "mission_fit": 17,
            "evidence_density": 13,
            "implementation_leverage": 15,
            "self_hostability": 9,
            "composability": 10,
            "maintenance_health": 8,
            "baggage_penalty": -3,
            "adoption_clarity": 8,
        },
        score_rationale=[
            "Strong staged-citation workflow signal beyond flat deep-research loops.",
            "Useful for explicit research-vs-writing boundaries.",
        ],
        avoid_copying=[
            "Do not inherit article-generation assumptions as the primary product shape.",
            "Do not collapse evidence collection back into prose-first output.",
        ],
    ),
    CatalogEntry(
        candidate_id="paperqa2",
        name="PaperQA2",
        candidate_type="system",
        repository_url="https://github.com/Future-House/paper-qa",
        homepage_url="https://github.com/Future-House/paper-qa",
        repository_last_pushed_at="2026-03-29T00:00:00+00:00",
        repository_stars=9800,
        repository_forks=760,
        repository_open_issues=110,
        latest_release_published_at="2026-03-21T00:00:00+00:00",
        releases_last_180d=7,
        summary="Citation-grounded evidence-ranking system with metadata enrichment and reusable indexing.",
        problem_solved="Improves evidence ranking, source limiting, metadata enrichment, and citation-grounded answer assembly.",
        value_hypothesis="Useful source-intelligence signal for explicit evidence discipline rather than report-only behavior.",
        baggage_signals=["Scientific-corpus bias", "Paper/PDF-heavy defaults"],
        adoption_target_hint="discovery",
        usefulness_level_hint="direct",
        capability_gap_hint="Need stronger evidence ranking, trust signals, and citation discipline.",
        keywords=["evidence ranking", "citation", "metadata", "crossref", "semantic scholar", "index", "retrieval"],
        facts=[
            CatalogFact("architecture", "high", "Supports metadata lookup, citation counts, retraction checks, and reusable indexes."),
            CatalogFact("workflow", "high", "Separates corpus preparation, evidence retrieval, and cited answer generation."),
            CatalogFact("integration", "medium", "Supports HTML and code inputs in addition to traditional papers."),
            CatalogFact("dependency", "medium", "Academic metadata assumptions may need adaptation for engineering sources."),
        ],
        score_hint={
            "mission_fit": 19,
            "evidence_density": 14,
            "implementation_leverage": 16,
            "self_hostability": 9,
            "composability": 11,
            "maintenance_health": 8,
            "baggage_penalty": -3,
            "adoption_clarity": 9,
        },
        score_rationale=[
            "Strongest evidence-discipline signal in the deterministic source pool.",
            "Useful for metadata-aware source scoring and citation control.",
        ],
        avoid_copying=[
            "Do not assume the source pool is mostly PDFs or papers.",
            "Do not overfit trust signals to academic metadata only.",
        ],
    ),
    CatalogEntry(
        candidate_id="fathom-deep-research",
        name="Fathom-DeepResearch",
        candidate_type="system",
        repository_url="https://github.com/FractalAIResearchLabs/Fathom-DeepResearch",
        homepage_url="https://github.com/FractalAIResearchLabs/Fathom-DeepResearch",
        repository_last_pushed_at="2026-03-30T00:00:00+00:00",
        repository_stars=4200,
        repository_forks=310,
        repository_open_issues=40,
        latest_release_published_at="2026-03-22T00:00:00+00:00",
        releases_last_180d=4,
        summary="Long-horizon deep-research system with explicit search-backend and synthesizer separation.",
        problem_solved="Separates live-web evidence seeking from final synthesis instead of collapsing both into one agent loop.",
        value_hypothesis="Useful source-intelligence signal for bounded acquisition-vs-synthesis separation and heterogeneous search handling.",
        baggage_signals=["Benchmark/model-stack coupling", "Thinner public subsystem docs"],
        adoption_target_hint="discovery",
        usefulness_level_hint="structural",
        capability_gap_hint="Need cleaner separation between acquisition backend and synthesis/report layers.",
        keywords=["deep research", "search backend", "synthesizer", "web search", "web visit", "heterogeneous sources"],
        facts=[
            CatalogFact("workflow", "high", "Uses specialized search and synthesis paths rather than one undifferentiated loop."),
            CatalogFact("architecture", "medium", "Exposes search-tool server and distinct web search/web visit surfaces."),
            CatalogFact("signal", "medium", "Good signal for live-web evidence seeking and search/synthesis separation."),
            CatalogFact("dependency", "medium", "Public repo surface is thinner than more mature framework-style systems."),
        ],
        score_hint={
            "mission_fit": 18,
            "evidence_density": 12,
            "implementation_leverage": 15,
            "self_hostability": 9,
            "composability": 11,
            "maintenance_health": 8,
            "baggage_penalty": -3,
            "adoption_clarity": 8,
        },
        score_rationale=[
            "Strong live-web acquisition-vs-synthesis separation signal.",
            "Useful when evaluating long-horizon research workflow boundaries.",
        ],
        avoid_copying=[
            "Do not inherit model-specific stack complexity into the core engine.",
            "Do not mistake benchmark framing for bounded subsystem design.",
        ],
    ),
    CatalogEntry(
        candidate_id="microsoft-graphrag",
        name="Microsoft GraphRAG",
        candidate_type="framework",
        repository_url="https://github.com/microsoft/graphrag",
        homepage_url="https://microsoft.github.io/graphrag/query/overview/",
        repository_last_pushed_at="2026-03-27T00:00:00+00:00",
        repository_stars=25000,
        repository_forks=1900,
        repository_open_issues=220,
        latest_release_published_at="2026-03-14T00:00:00+00:00",
        releases_last_180d=6,
        summary="Graph-based retrieval pipeline with local, global, and DRIFT search over structured evidence indexes.",
        problem_solved="Adds richer post-acquisition evidence memory and multi-mode retrieval over accumulated corpora.",
        value_hypothesis="Useful source-intelligence signal for structured evidence memory rather than flat chunk retrieval.",
        baggage_signals=["Heavy indexing footprint", "Corpus-first orientation"],
        adoption_target_hint="discovery",
        usefulness_level_hint="structural",
        capability_gap_hint="Need richer evidence memory and multi-hop retrieval over accumulated technical sources.",
        keywords=["graph rag", "evidence memory", "local search", "global search", "drift search", "question generation"],
        facts=[
            CatalogFact("architecture", "high", "Transforms unstructured text into structured graph artifacts for downstream query modes."),
            CatalogFact("workflow", "high", "Supports local, global, DRIFT, and basic search plus question generation."),
            CatalogFact("integration", "medium", "Good fit for post-acquisition evidence exploration over completed indexes."),
            CatalogFact("dependency", "medium", "Indexing cost and corpus-first assumptions add significant operational weight."),
        ],
        score_hint={
            "mission_fit": 15,
            "evidence_density": 13,
            "implementation_leverage": 14,
            "self_hostability": 9,
            "composability": 9,
            "maintenance_health": 8,
            "baggage_penalty": -4,
            "adoption_clarity": 7,
        },
        score_rationale=[
            "Strong evidence-memory signal beyond flat retrieval loops.",
            "Best interpreted as a structured-memory reference, not as raw source acquisition.",
        ],
        avoid_copying=[
            "Do not start with full graph indexing before validating core acquisition quality.",
            "Do not treat corpus retrieval as a replacement for fresh source-finding.",
        ],
    ),
    CatalogEntry(
        candidate_id="arize-phoenix",
        name="Arize Phoenix",
        candidate_type="platform",
        repository_url="https://github.com/Arize-ai/phoenix",
        homepage_url="https://phoenix.arize.com/",
        repository_last_pushed_at="2026-03-29T00:00:00+00:00",
        repository_stars=6400,
        repository_forks=430,
        repository_open_issues=150,
        latest_release_published_at="2026-03-19T00:00:00+00:00",
        releases_last_180d=10,
        summary="Open-source observability and evaluation system for tracing retrieval and generation workflows.",
        problem_solved="Improves run inspectability, evaluation, and debugging for evidence retrieval and research pipelines.",
        value_hypothesis="Useful source-intelligence signal for trace/eval surfaces around the core pipeline.",
        baggage_signals=["Operational add-on rather than core acquisition logic", "Observability platform scope"],
        adoption_target_hint="reference",
        usefulness_level_hint="meta",
        capability_gap_hint="Need inspectable run evidence and eval surfaces around research runs.",
        keywords=["observability", "tracing", "evaluation", "datasets", "experiments", "retrieval"],
        facts=[
            CatalogFact("workflow", "medium", "Provides tracing and evaluation surfaces for AI pipelines rather than acquisition logic itself."),
            CatalogFact("integration", "high", "Built on OpenTelemetry and positioned as vendor/framework agnostic."),
            CatalogFact("signal", "medium", "Strong signal for run evidence and retrieval debugging."),
            CatalogFact("dependency", "medium", "Operational scope is wider than a bounded source-intelligence core."),
        ],
        score_hint={
            "mission_fit": 12,
            "evidence_density": 11,
            "implementation_leverage": 11,
            "self_hostability": 9,
            "composability": 9,
            "maintenance_health": 8,
            "baggage_penalty": -3,
            "adoption_clarity": 7,
        },
        score_rationale=[
            "Strong observability signal for retrieval/evidence pipelines.",
            "Indirect to source acquisition itself, but useful for inspection and evals.",
        ],
        avoid_copying=[
            "Do not substitute observability for actual evidence-quality improvements.",
            "Do not deploy full platform weight before the core pipeline is stable.",
        ],
    ),
    CatalogEntry(
        candidate_id="langgraph",
        name="LangGraph",
        candidate_type="framework",
        repository_url="https://github.com/langchain-ai/langgraph",
        homepage_url="https://docs.langchain.com/oss/javascript/langgraph/durable-execution",
        repository_last_pushed_at="2026-03-29T00:00:00+00:00",
        repository_stars=19000,
        repository_forks=1600,
        repository_open_issues=210,
        latest_release_published_at="2026-03-25T00:00:00+00:00",
        releases_last_180d=12,
        summary="Durable workflow runtime with checkpoints, interrupts, and resumable execution semantics.",
        problem_solved="Adds resumable, inspectable execution for long-running or interruptible research runs.",
        value_hypothesis="Useful source-intelligence signal for run durability and stateful research orchestration.",
        baggage_signals=["Generic workflow runtime", "Framework-flavored orchestration"],
        adoption_target_hint="reference",
        usefulness_level_hint="meta",
        capability_gap_hint="Need durable execution and pause/resume semantics for research runs.",
        keywords=["durable execution", "checkpoint", "interrupt", "resume", "thread", "workflow"],
        facts=[
            CatalogFact("workflow", "high", "Supports checkpoint persistence, thread identity, and interrupt/resume semantics."),
            CatalogFact("architecture", "medium", "Provides explicit execution-state surfaces for long-running graph workflows."),
            CatalogFact("signal", "medium", "Useful durability signal when research runs need recovery and operator control."),
            CatalogFact("dependency", "medium", "Runtime is generic rather than source-intelligence specific."),
        ],
        score_hint={
            "mission_fit": 14,
            "evidence_density": 12,
            "implementation_leverage": 13,
            "self_hostability": 9,
            "composability": 10,
            "maintenance_health": 9,
            "baggage_penalty": -3,
            "adoption_clarity": 7,
        },
        score_rationale=[
            "Clear durability signal for long-running research execution.",
            "Less direct than acquisition or evidence-ranking systems.",
        ],
        avoid_copying=[
            "Do not turn the engine into a generic agent-graph shell.",
            "Do not over-center workflow runtime before evidence quality is proven.",
        ],
    ),
    CatalogEntry(
        candidate_id="crawl4ai",
        name="Crawl4AI",
        candidate_type="framework",
        repository_url="https://github.com/unclecode/crawl4ai",
        homepage_url="https://github.com/unclecode/crawl4ai",
        repository_last_pushed_at="2026-03-30T00:00:00+00:00",
        repository_stars=32000,
        repository_forks=2400,
        repository_open_issues=330,
        latest_release_published_at="2026-03-26T00:00:00+00:00",
        releases_last_180d=14,
        summary="LLM-friendly acquisition and extraction framework with markdown conversion, citations, and structured extraction.",
        problem_solved="Improves source acquisition, page normalization, and structured extraction for technical web sources.",
        value_hypothesis="Useful source-intelligence signal for bounded fetch/extract/normalize substrate quality.",
        baggage_signals=["Crawler-platform surface area", "Acquisition-only focus"],
        adoption_target_hint="discovery",
        usefulness_level_hint="direct",
        capability_gap_hint="Need stronger fetch, extraction, and normalization for mixed web sources.",
        keywords=["crawl", "markdown", "structured extraction", "citation", "session management", "acquisition"],
        facts=[
            CatalogFact("workflow", "high", "Supports markdown conversion, citation/reference generation, and structured extraction."),
            CatalogFact("architecture", "medium", "Includes session management and multi-step crawling surfaces."),
            CatalogFact("integration", "medium", "Strong fit as a bounded acquisition and normalization layer."),
            CatalogFact("dependency", "medium", "Broader crawling/platform scope can exceed bounded source-intelligence needs."),
        ],
        score_hint={
            "mission_fit": 18,
            "evidence_density": 13,
            "implementation_leverage": 15,
            "self_hostability": 10,
            "composability": 11,
            "maintenance_health": 9,
            "baggage_penalty": -3,
            "adoption_clarity": 9,
        },
        score_rationale=[
            "Strongest acquisition and normalization substrate signal in the deterministic pool.",
            "Useful for fetch/extract mechanics without inventing a crawler stack from scratch.",
        ],
        avoid_copying=[
            "Do not let acquisition scope expand into a general crawler platform.",
            "Do not confuse raw extraction strength with evidence-ranking quality.",
        ],
    ),
    CatalogEntry(
        candidate_id="salesforce-enterprise-deep-research",
        name="Salesforce Enterprise Deep Research",
        candidate_type="system",
        repository_url="https://github.com/SalesforceAIResearch/enterprise-deep-research",
        homepage_url="https://github.com/SalesforceAIResearch/enterprise-deep-research",
        repository_last_pushed_at="2026-03-28T00:00:00+00:00",
        repository_stars=2100,
        repository_forks=140,
        repository_open_issues=24,
        latest_release_published_at="2026-03-20T00:00:00+00:00",
        releases_last_180d=3,
        summary="Multi-agent enterprise research system with planning, specialized search roles, reflection, and steering.",
        problem_solved="Adds reflection loops, specialized search roles, and steering/control surfaces for research trajectories.",
        value_hypothesis="Useful source-intelligence signal for control-plane and reflection concepts around research runs.",
        baggage_signals=["Enterprise-oriented control-plane bulk", "Benchmark-heavy framing"],
        adoption_target_hint="reference",
        usefulness_level_hint="meta",
        capability_gap_hint="Need clearer reflection and steering signals for research control surfaces.",
        keywords=["multi-agent", "planning", "reflection", "steering", "citation management", "search agents"],
        facts=[
            CatalogFact("workflow", "high", "Combines planning, specialized search agents, reflection, and steering commands."),
            CatalogFact("architecture", "medium", "Uses MCP-based tools and explicit role decomposition."),
            CatalogFact("signal", "medium", "Good signal for trajectory logging, operator steering, and reflection loops."),
            CatalogFact("dependency", "medium", "Enterprise control-plane surface may add substantial adoption baggage."),
        ],
        score_hint={
            "mission_fit": 13,
            "evidence_density": 11,
            "implementation_leverage": 12,
            "self_hostability": 9,
            "composability": 8,
            "maintenance_health": 8,
            "baggage_penalty": -4,
            "adoption_clarity": 6,
        },
        score_rationale=[
            "Interesting reflection/control-plane signal around research trajectories.",
            "Reusable bounded subsystem value is less clear than acquisition or evidence-specific systems.",
        ],
        avoid_copying=[
            "Do not inherit enterprise control-plane bulk into a bounded research packet pipeline.",
            "Do not overbuild agent roles before source intelligence is solid.",
        ],
    ),
    CatalogEntry(
        candidate_id="dzhng-deep-research",
        name="dzhng/deep-research",
        candidate_type="system",
        repository_url="https://github.com/dzhng/deep-research",
        homepage_url="https://github.com/dzhng/deep-research",
        repository_last_pushed_at="2026-03-22T00:00:00+00:00",
        repository_stars=9000,
        repository_forks=950,
        repository_open_issues=80,
        latest_release_published_at="2026-03-10T00:00:00+00:00",
        releases_last_180d=7,
        summary="Minimal deep-research implementation built around bounded recursive discovery.",
        problem_solved="Shows the smallest useful recursive research loop that still goes beyond one-shot search.",
        value_hypothesis="Best simplification reference because it proves how little machinery is required for a useful research pass.",
        baggage_signals=["Thin normalization layer", "Weak candidate model"],
        adoption_target_hint="discovery",
        usefulness_level_hint="structural",
        capability_gap_hint="Need bounded recursion and minimal plumbing without overbuilding a generic agent runtime.",
        keywords=["minimal", "recursive search", "bounded research", "firecrawl", "hackable", "small codebase"],
        facts=[
            CatalogFact("workflow", "high", "Uses bounded recursive search to deepen discovery without requiring an elaborate agent framework."),
            CatalogFact("architecture", "medium", "Keeps code size small enough for a solo builder to study and modify quickly."),
            CatalogFact("dependency", "medium", "Relies heavily on external acquisition services instead of rebuilding infrastructure."),
            CatalogFact("signal", "medium", "Needs stronger artifact and scoring layers before it can feed DW-style decisions."),
        ],
        score_hint={
            "mission_fit": 16,
            "evidence_density": 12,
            "implementation_leverage": 16,
            "self_hostability": 9,
            "composability": 11,
            "maintenance_health": 7,
            "baggage_penalty": -4,
            "adoption_clarity": 7,
        },
        score_rationale=[
            "Best simplification pressure in the source pool.",
            "Good fit for a solo-builder-friendly first implementation.",
            "Needs a stronger evidence schema than the original project provides.",
        ],
        avoid_copying=["Do not inherit report-only outputs.", "Do not inherit the absence of explicit candidate dossiers."],
    ),
    CatalogEntry(
        candidate_id="local-deep-researcher",
        name="local-deep-researcher",
        candidate_type="system",
        repository_url="https://github.com/langchain-ai/local-deep-researcher",
        homepage_url="https://github.com/langchain-ai/local-deep-researcher",
        repository_last_pushed_at="2025-11-15T00:00:00+00:00",
        repository_stars=3000,
        repository_forks=350,
        repository_open_issues=40,
        latest_release_published_at="2025-10-02T00:00:00+00:00",
        releases_last_180d=2,
        summary="Readable local-first research loop that emphasizes reflect-and-refine behavior.",
        problem_solved="Demonstrates a simple iterative loop for improving search and summaries with smaller or local models.",
        value_hypothesis="Useful as an optional later-mode reference for privacy-sensitive or offline-ish research passes.",
        baggage_signals=["Local-first constraint would weaken V1 discovery quality", "Shallower discovery power"],
        adoption_target_hint="monitor",
        usefulness_level_hint="meta",
        capability_gap_hint="Need a fallback path for local-first environments later, not as the primary initial stack.",
        keywords=["local-first", "reflect", "refine", "small models", "iterative loop"],
        facts=[
            CatalogFact("workflow", "medium", "Has a clean query-search-summarize-reflect loop that can inspire a later enrichment pass."),
            CatalogFact("architecture", "medium", "Readable structure makes it a good fallback reference when simplifying refinement logic."),
            CatalogFact("signal", "medium", "Not strong enough as the main base for source-seeking discovery."),
            CatalogFact("maintenance", "low", "Local-first design is valuable later but would constrain V1 too early."),
        ],
        score_hint={
            "mission_fit": 12,
            "evidence_density": 10,
            "implementation_leverage": 12,
            "self_hostability": 12,
            "composability": 9,
            "maintenance_health": 6,
            "baggage_penalty": -4,
            "adoption_clarity": 7,
        },
        score_rationale=[
            "Good later-mode reference for local-first operation.",
            "Not strong enough for primary Research Engine discovery quality.",
        ],
        avoid_copying=["Do not make local-first a V1 requirement.", "Do not inherit summarizer-first framing."],
    ),
    CatalogEntry(
        candidate_id="vane",
        name="Vane",
        candidate_type="system",
        repository_url="https://github.com/ItzCrazyKns/Vane",
        homepage_url="https://github.com/ItzCrazyKns/Vane",
        repository_last_pushed_at="2025-07-10T00:00:00+00:00",
        repository_stars=1200,
        repository_forks=140,
        repository_open_issues=95,
        latest_release_published_at="2025-05-12T00:00:00+00:00",
        releases_last_180d=1,
        summary="Self-hosted answer-engine product with practical private-search UX patterns.",
        problem_solved="Provides productized search-answer flows and domain-limited source modes.",
        value_hypothesis="Useful only for search UX ideas and source-mode ergonomics, not as the base architecture.",
        baggage_signals=["UI-heavy codebase", "Answer-first product framing", "Snippet-oriented search loop"],
        adoption_target_hint="reference",
        usefulness_level_hint="meta",
        capability_gap_hint="Need limited inspiration for inspectable search-step UX, not core acquisition logic.",
        keywords=["answer engine", "ui", "search mode", "searxng", "product", "private search"],
        facts=[
            CatalogFact("signal", "medium", "Shows practical search-mode routing and visible research-step streaming."),
            CatalogFact("architecture", "medium", "Core structure is product-shell heavy rather than logic-core heavy."),
            CatalogFact("workflow", "low", "Search loop is optimized for answering, not for structured evidence assembly."),
            CatalogFact("dependency", "medium", "Carrying its UI and product concerns into Research Engine would be baggage."),
        ],
        score_hint={
            "mission_fit": 8,
            "evidence_density": 8,
            "implementation_leverage": 9,
            "self_hostability": 11,
            "composability": 6,
            "maintenance_health": 6,
            "baggage_penalty": -7,
            "adoption_clarity": 6,
        },
        score_rationale=["Useful inspiration for UX only.", "Weak fit for evidence-oriented Research Engine core logic."],
        avoid_copying=["Do not inherit chat shell or answer-first architecture.", "Do not inherit UI-heavy product scaffolding."],
        rejection_reason="Reject as a core base because it solves a consumer-style answer flow more than a candidate-and-evidence acquisition problem.",
        reconsider_if="Reconsider only when Research Engine needs a thin inspection UI for search modes.",
    ),
]


def get_catalog_entry(candidate_id: str) -> CatalogEntry:
    for entry in REFERENCE_CATALOG:
        if entry.candidate_id == candidate_id:
            return entry
    raise KeyError(candidate_id)
