import fs from "node:fs";
import path from "node:path";

type JsonValue = Record<string, unknown>;

export const DEFAULT_STANDALONE_BOOTSTRAP_CONFIG_FILENAME =
  "standalone-host.config.json";
export const DEFAULT_STANDALONE_BOOTSTRAP_EXAMPLE_SUBMISSION_FILENAME =
  "discovery-submission.queue-only.example.json";
export const DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_FOLLOW_UP_FILENAME =
  "runtime-follow-up.example.json";
export const DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_RECORD_FILENAME =
  "runtime-record.example.json";
export const DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_PROOF_FILENAME =
  "runtime-proof-bundle.example.json";
export const DEFAULT_STANDALONE_BOOTSTRAP_TRANSFORMATION_PROOF_FILENAME =
  "runtime-transformation-proof.example.json";
export const DEFAULT_STANDALONE_BOOTSTRAP_TRANSFORMATION_RECORD_FILENAME =
  "runtime-transformation-record.example.json";
export const DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_PROMOTION_FILENAME =
  "runtime-promotion-record.example.json";
export const DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_REGISTRY_FILENAME =
  "runtime-registry-entry.example.json";
export const DEFAULT_STANDALONE_BOOTSTRAP_README_FILENAME = "README.md";

export type BootstrapStandaloneHostWorkspaceOptions = {
  outputRoot: string;
  hostName?: string;
  receivedAt?: string;
  configFilename?: string;
  includeSqlitePersistence?: boolean;
  includeAuthTemplate?: boolean;
};

export type BootstrapStandaloneHostWorkspaceResult = {
  outputRoot: string;
  directiveRoot: string;
  configPath: string;
  readmePath: string;
  exampleSubmissionPath: string;
  exampleRuntimeFollowUpPath: string;
  exampleRuntimeRecordPath: string;
  exampleRuntimeProofPath: string;
  exampleTransformationProofPath: string;
  exampleTransformationRecordPath: string;
  exampleRuntimePromotionPath: string;
  exampleRuntimeRegistryPath: string;
  createdPaths: string[];
};

function normalizeAbsolutePath(filePath: string) {
  return path.resolve(filePath).replace(/\\/g, "/");
}

function ensureDirectory(filePath: string) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function writeJson(filePath: string, value: unknown) {
  ensureDirectory(filePath);
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function writeText(filePath: string, content: string) {
  ensureDirectory(filePath);
  fs.writeFileSync(filePath, content, "utf8");
}

function createInitialQueue(receivedAt: string): JsonValue {
  return {
    status: "primary",
    updatedAt: receivedAt,
    entries: [],
  };
}

function createExampleSubmission(receivedAt: string): JsonValue {
  return {
    candidate_id: "dw-bootstrap-queue-only-example",
    candidate_name: "Bootstrap Queue-Only Discovery Candidate",
    source_type: "internal-signal",
    source_reference: "host://bootstrap/discovery-queue-only-example",
    mission_alignment:
      "Shows a minimal Discovery submission that outside GitHub/local users can run immediately after bootstrap.",
    capability_gap_id: null,
    notes: `Generated by standalone-host init on ${receivedAt}.`,
    record_shape: "queue_only",
  };
}

function createRuntimeFollowUpExample(receivedAt: string): JsonValue {
  return {
    candidate_id: "dw-bootstrap-runtime-example",
    candidate_name: "Bootstrap Runtime Example",
    follow_up_date: receivedAt,
    current_decision_state: "accepted_for_bounded_local_follow_up",
    origin_track: "architecture",
    runtime_value_to_operationalize:
      "Create a bounded Runtime follow-up from a standalone local/shareable host without Mission Control.",
    proposed_host: "directive-workspace-standalone-host",
    proposed_integration_mode: "local_shareable_workflow",
    source_pack_allowlist_profile: "n/a",
    allowed_export_surfaces: [
      "@directive-workspace/product/standalone-host",
      "@directive-workspace/product/standalone-host/runtime",
    ],
    excluded_baggage: [
      "broad runtime promotion claims",
      "Mission Control-specific host assumptions",
    ],
    promotion_contract_path: "shared/contracts/host-integration-boundary.md",
    reentry_preconditions: [
      "confirm the local workflow stays bounded and reversible",
      "keep filesystem artifacts canonical even when SQLite is enabled",
    ],
    required_proof: [
      "runtime/follow-up and runtime/records artifacts can be written locally",
      "standalone host can report Runtime overview without Mission Control",
    ],
    required_gates: [
      "check:directive-standalone-runtime-host",
    ],
    trial_scope_limit: [
      "markdown workflow artifacts only",
      "no runtime promotion",
    ],
    risks: [
      "example payloads still need real source-specific details before any live promotion decision",
    ],
    rollback:
      "Delete the generated Runtime follow-up and any linked local example artifacts.",
    no_op_path:
      "Keep using the standalone host for Discovery only until a real Runtime slice is needed.",
    review_cadence: "review on the next standalone-host completeness pass",
    current_status: "follow_up_only",
  };
}

function createRuntimeRecordExample(receivedAt: string): JsonValue {
  return {
    candidate_id: "dw-bootstrap-runtime-example",
    candidate_name: "Bootstrap Runtime Example",
    runtime_record_date: receivedAt,
    origin_path: `architecture/02-adopted/${receivedAt}-bootstrap-runtime-example-origin.md`,
    linked_follow_up_record:
      `runtime/00-follow-up/${receivedAt}-dw-bootstrap-runtime-example-runtime-follow-up-record.md`,
    runtime_objective:
      "Materialize the first bounded Runtime record from the standalone host's local/shareable surface.",
    proposed_host: "directive-workspace-standalone-host",
    proposed_runtime_surface: "local markdown-defined runtime workflow",
    execution_slice:
      "Write a bounded Runtime record and expose it through the standalone host overview/API without claiming runtime parity.",
    required_proof:
      `runtime/legacy-records/${receivedAt}-dw-bootstrap-runtime-example-proof-checklist.md`,
    required_gates: [
      "check:directive-standalone-runtime-host",
    ],
    risks: [
      "example origin paths are placeholders and should be replaced for real work",
    ],
    rollback:
      "Delete the generated Runtime record and linked follow-up if the example is no longer useful.",
    current_status: "follow_up_only",
    next_decision_point:
      "After local review, decide whether to open a real bounded runtime slice.",
    supporting_contracts: [
      "shared/contracts/host-integration-boundary.md",
      "shared/contracts/standalone-host-runtime-profile.md",
    ],
  };
}

function createRuntimeProofExample(receivedAt: string): JsonValue {
  return {
    candidate_id: "dw-bootstrap-runtime-example",
    candidate_name: "Bootstrap Runtime Example",
    proof_date: receivedAt,
    linked_runtime_record:
      `runtime/legacy-records/${receivedAt}-dw-bootstrap-runtime-example-runtime-record.md`,
    required_proof_items: [
      "Runtime record exists",
      "Gate snapshot JSON exists",
      "Rollback verification note is captured",
    ],
    validation_commands: [
      "check:directive-standalone-runtime-host",
      "check:directive-standalone-api-host",
    ],
    source_proof_artifacts: [
      `runtime/00-follow-up/${receivedAt}-dw-bootstrap-runtime-example-runtime-follow-up-record.md`,
      `runtime/legacy-records/${receivedAt}-dw-bootstrap-runtime-example-runtime-record.md`,
    ],
    gate_snapshot: {
      overall_result: "pass",
      evaluated_gates: [
        {
          command: "check:directive-standalone-runtime-host",
          result: "pass",
        },
        {
          command: "check:directive-standalone-api-host",
          result: "pass",
        },
      ],
      evidence: [
        "local artifact lifecycle written",
        "Runtime overview reports follow-up, record, proof, promotion, and registry state",
      ],
    },
    pass_fail_summary:
      "Bounded standalone Runtime proof bundle generated locally with passing host and API evidence.",
    rollback_verification:
      "Delete the proof checklist, gate snapshot JSON, and linked local Runtime artifacts to roll back the example cleanly.",
    status: "validated_locally",
  };
}

function createTransformationProofExample(receivedAt: string): JsonValue {
  return {
    candidate_id: "dw-bootstrap-transformation-example",
    candidate_name: "Bootstrap Transformation Example",
    proof_date: receivedAt,
    transformation_type: "maintainability",
    preservation_claim:
      "The standalone transformation lane must preserve the described workflow behavior while improving product-owned execution discipline.",
    baseline_measurement: {
      metric: "manual_transformation_recording_steps",
      value: 2,
      measurement_method:
        "Count the separate proof and record artifacts that previously required hand-authored formatting.",
    },
    result_measurement: {
      metric: "manual_transformation_recording_steps",
      value: 1,
      measurement_method:
        "Count the standalone-host proof write needed once a canonical transformation-proof writer exists.",
    },
    comparison_summary:
      "The proof artifact moves from hand-authored JSON to one canonical product-owned writer while preserving the transformation-proof schema shape.",
    rollback_verification:
      "Delete the generated transformation proof and transformation record artifacts to return the local bundle to its pre-example state.",
    regression_checks: [
      {
        check_name: "check:directive-standalone-runtime-host",
        result: "pass",
      },
    ],
  };
}

function createTransformationRecordExample(receivedAt: string): JsonValue {
  return {
    candidate_id: "dw-bootstrap-transformation-example",
    candidate_name: "Bootstrap Transformation Example",
    record_date: receivedAt,
    transformation_type: "maintainability",
    discovery_intake_path:
      `discovery/01-intake/${receivedAt}-bootstrap-transformation-intake.md`,
    component: "standalone-host Runtime transformation lane",
    current_implementation:
      "Transformation artifacts existed as templates and historical records without a canonical standalone-host writer path.",
    baseline_metric: "manual_transformation_recording_steps",
    baseline_value: "2",
    baseline_measurement_method:
      "count proof artifact authoring plus transformation record authoring before the standalone transformation helper existed",
    proposed_change:
      "Add canonical transformation-proof and transformation-record writers plus standalone-host CLI/API support.",
    preservation_claim:
      "Keep the transformation-proof schema shape and the transformation-record operating fields while making emission product-owned.",
    expected_improvement_metric: "manual_transformation_recording_steps",
    expected_target_value: "1",
    expected_measurement_method:
      "count the remaining operator step once canonical writers exist",
    evaluator_type: "automated",
    evaluator_command:
      "npm run check:directive-standalone-runtime-host && npm run check:directive-standalone-api-host",
    comparison_mode: "before-after",
    baseline_artifact_path:
      `runtime/legacy-records/${receivedAt}-dw-bootstrap-transformation-example-transformation-proof.json`,
    result_artifact_path:
      `runtime/legacy-records/${receivedAt}-dw-bootstrap-transformation-example-transformation-proof.json`,
    correctness_preserved:
      "yes - the transformation proof still satisfies the canonical schema and the standalone host still stays bounded/local",
    metric_improvement_measured:
      "yes - one canonical helper now emits the transformation proof artifact shape",
    rollback_path:
      "Delete the generated transformation proof and transformation record artifacts.",
    rollback_tested: "yes - bounded local artifacts only",
    decision_state: "evaluated",
    mission_alignment:
      "Improve Runtime's behavior-preserving transformation lane as part of Directive Workspace system quality.",
    capability_gap_id: "gap-transformation-lane",
  };
}

function createRuntimePromotionExample(receivedAt: string): JsonValue {
  return {
    candidate_id: "dw-bootstrap-runtime-example",
    candidate_name: "Bootstrap Runtime Example",
    promotion_date: receivedAt,
    linked_runtime_record:
      `runtime/legacy-records/${receivedAt}-dw-bootstrap-runtime-example-runtime-record.md`,
    target_host: "directive-workspace-standalone-host",
    target_runtime_surface: "bounded local runtime artifact lifecycle",
    integration_mode: "reimplement",
    source_intent_artifact:
      `runtime/00-follow-up/${receivedAt}-dw-bootstrap-runtime-example-runtime-follow-up-record.md`,
    compile_contract_artifact: "shared/contracts/runtime-to-host.md",
    runtime_permissions_profile: "local_filesystem_only",
    safe_output_scope: "directive-root/runtime/**",
    sanitize_policy: "no_external_network_side_effects",
    proposed_runtime_status: "bounded_local_reference",
    proof_path:
      `runtime/legacy-records/${receivedAt}-dw-bootstrap-runtime-example-proof-checklist.md`,
    quality_gate_profile: "bounded_local_reference_guard/v1",
    promotion_profile_family: "bounded_local_reference",
    proof_shape: "runtime_local_artifact_proof/v1",
    primary_host_checker: "npm run check:directive-standalone-runtime-host",
    full_text_coverage_threshold: "0",
    evidence_binding_threshold: "100",
    citation_error_threshold: "0",
    observed_full_text_coverage: "0",
    observed_evidence_binding: "100",
    observed_citation_error_rate: "0",
    quality_gate_result: "pass",
    validation_state: "validated_locally",
    quality_gate_fail_reasons: [],
    required_gates: [
      "check:directive-standalone-runtime-host",
      "check:directive-standalone-api-host",
    ],
    validation_result:
      "Standalone host can write and read the full bounded Runtime artifact lifecycle locally.",
    rollback_plan:
      "Delete the generated promotion record and related local Runtime artifacts.",
    owner: "Directive Runtime",
    promotion_decision: "approved_for_bounded_local_reference_use",
  };
}

function createRuntimeRegistryExample(receivedAt: string): JsonValue {
  return {
    candidate_id: "dw-bootstrap-runtime-example",
    candidate_name: "Bootstrap Runtime Example",
    registry_date: receivedAt,
    linked_promotion_record:
      `runtime/07-promotion-records/${receivedAt}-dw-bootstrap-runtime-example-promotion-record.md`,
    host: "directive-workspace-standalone-host",
    runtime_surface: "bounded local runtime artifact lifecycle",
    runtime_status: "reference_live",
    proof_path:
      `runtime/legacy-records/${receivedAt}-dw-bootstrap-runtime-example-proof-checklist.md`,
    last_validated_by: "check:directive-standalone-runtime-host",
    last_validation_date: receivedAt,
    active_risks: [
      "local reference lane only",
      "not a broad Mission Control replacement",
    ],
    rollback_path:
      "Delete the generated registry entry and revert the local Runtime lifecycle artifacts.",
    notes: [
      "This example is for bounded local/shareable usage.",
      "Generate the proof bundle before using this for real promotion history.",
    ],
  };
}

function renderBootstrapReadme(input: {
  hostName: string;
  outputRoot: string;
  configFilename: string;
  receivedAt: string;
  includeSqlitePersistence: boolean;
  includeAuthTemplate: boolean;
}) {
  return `# ${input.hostName}

This folder was bootstrapped by Directive Workspace standalone host init.

Generated:
- ${input.receivedAt}

Contents:
- \`${input.configFilename}\` - standalone host config
- \`directive-root/\` - local Directive root for Discovery/runtime artifacts
- \`${DEFAULT_STANDALONE_BOOTSTRAP_EXAMPLE_SUBMISSION_FILENAME}\` - queue-only Discovery submission example
- \`${DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_FOLLOW_UP_FILENAME}\` - Runtime follow-up example
- \`${DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_RECORD_FILENAME}\` - Runtime record example
- \`${DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_PROOF_FILENAME}\` - Runtime proof bundle example
- \`${DEFAULT_STANDALONE_BOOTSTRAP_TRANSFORMATION_PROOF_FILENAME}\` - Runtime transformation proof example
- \`${DEFAULT_STANDALONE_BOOTSTRAP_TRANSFORMATION_RECORD_FILENAME}\` - Runtime transformation record example
- \`${DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_PROMOTION_FILENAME}\` - Runtime promotion record example
- \`${DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_REGISTRY_FILENAME}\` - Runtime registry entry example

Quickstart:
Run these from the Directive Workspace repo root:
1. \`tsx hosts/standalone-host/cli.ts discovery-submit --config ${input.outputRoot}/${input.configFilename} --input-json-path ${input.outputRoot}/${DEFAULT_STANDALONE_BOOTSTRAP_EXAMPLE_SUBMISSION_FILENAME}\`
2. \`tsx hosts/standalone-host/cli.ts discovery-overview --config ${input.outputRoot}/${input.configFilename}\`
3. \`tsx hosts/standalone-host/cli.ts runtime-followup-write --config ${input.outputRoot}/${input.configFilename} --input-json-path ${input.outputRoot}/${DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_FOLLOW_UP_FILENAME}\`
4. \`tsx hosts/standalone-host/cli.ts runtime-record-write --config ${input.outputRoot}/${input.configFilename} --input-json-path ${input.outputRoot}/${DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_RECORD_FILENAME}\`
5. \`tsx hosts/standalone-host/cli.ts runtime-proof-write --config ${input.outputRoot}/${input.configFilename} --input-json-path ${input.outputRoot}/${DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_PROOF_FILENAME}\`
6. \`tsx hosts/standalone-host/cli.ts runtime-transformation-proof-write --config ${input.outputRoot}/${input.configFilename} --input-json-path ${input.outputRoot}/${DEFAULT_STANDALONE_BOOTSTRAP_TRANSFORMATION_PROOF_FILENAME}\`
7. \`tsx hosts/standalone-host/cli.ts runtime-transformation-record-write --config ${input.outputRoot}/${input.configFilename} --input-json-path ${input.outputRoot}/${DEFAULT_STANDALONE_BOOTSTRAP_TRANSFORMATION_RECORD_FILENAME}\`
8. \`tsx hosts/standalone-host/cli.ts runtime-promotion-write --config ${input.outputRoot}/${input.configFilename} --input-json-path ${input.outputRoot}/${DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_PROMOTION_FILENAME}\`
9. \`tsx hosts/standalone-host/cli.ts runtime-registry-write --config ${input.outputRoot}/${input.configFilename} --input-json-path ${input.outputRoot}/${DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_REGISTRY_FILENAME}\`
10. \`tsx hosts/standalone-host/cli.ts runtime-overview --config ${input.outputRoot}/${input.configFilename}\`
11. \`tsx hosts/standalone-host/cli.ts serve --config ${input.outputRoot}/${input.configFilename}\`

Notes:
- the host is local/shareable by design
- filesystem artifacts remain canonical
- SQLite persistence is ${
    input.includeSqlitePersistence ? "enabled" : "disabled"
  } in the generated config
- auth template is ${
    input.includeAuthTemplate ? "included" : "not included"
  } in the generated config
`;
}

export function bootstrapStandaloneHostWorkspace(
  options: BootstrapStandaloneHostWorkspaceOptions,
): BootstrapStandaloneHostWorkspaceResult {
  const outputRoot = normalizeAbsolutePath(options.outputRoot);
  const directiveRoot = normalizeAbsolutePath(
    path.resolve(outputRoot, "directive-root"),
  );
  const hostName = options.hostName ?? "Directive Workspace Standalone Host";
  const receivedAt = options.receivedAt ?? new Date().toISOString().slice(0, 10);
  const configFilename =
    options.configFilename ?? DEFAULT_STANDALONE_BOOTSTRAP_CONFIG_FILENAME;
  const configPath = normalizeAbsolutePath(path.resolve(outputRoot, configFilename));
  const queuePath = normalizeAbsolutePath(
    path.resolve(directiveRoot, "discovery", "intake-queue.json"),
  );
  const runtimeArtifactsDirectory = normalizeAbsolutePath(
    path.resolve(directiveRoot, "runtime", "standalone-host"),
  );
  const readmePath = normalizeAbsolutePath(
    path.resolve(outputRoot, DEFAULT_STANDALONE_BOOTSTRAP_README_FILENAME),
  );
  const exampleSubmissionPath = normalizeAbsolutePath(
    path.resolve(
      outputRoot,
      DEFAULT_STANDALONE_BOOTSTRAP_EXAMPLE_SUBMISSION_FILENAME,
    ),
  );
  const exampleRuntimeFollowUpPath = normalizeAbsolutePath(
    path.resolve(
      outputRoot,
      DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_FOLLOW_UP_FILENAME,
    ),
  );
  const exampleRuntimeRecordPath = normalizeAbsolutePath(
    path.resolve(
      outputRoot,
      DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_RECORD_FILENAME,
    ),
  );
  const exampleRuntimeProofPath = normalizeAbsolutePath(
    path.resolve(
      outputRoot,
      DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_PROOF_FILENAME,
    ),
  );
  const exampleTransformationProofPath = normalizeAbsolutePath(
    path.resolve(
      outputRoot,
      DEFAULT_STANDALONE_BOOTSTRAP_TRANSFORMATION_PROOF_FILENAME,
    ),
  );
  const exampleTransformationRecordPath = normalizeAbsolutePath(
    path.resolve(
      outputRoot,
      DEFAULT_STANDALONE_BOOTSTRAP_TRANSFORMATION_RECORD_FILENAME,
    ),
  );
  const exampleRuntimePromotionPath = normalizeAbsolutePath(
    path.resolve(
      outputRoot,
      DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_PROMOTION_FILENAME,
    ),
  );
  const exampleRuntimeRegistryPath = normalizeAbsolutePath(
    path.resolve(
      outputRoot,
      DEFAULT_STANDALONE_BOOTSTRAP_RUNTIME_REGISTRY_FILENAME,
    ),
  );
  const includeSqlitePersistence = options.includeSqlitePersistence !== false;
  const includeAuthTemplate = options.includeAuthTemplate === true;
  const runtimeFollowUpDirectory = normalizeAbsolutePath(
    path.resolve(directiveRoot, "runtime", "follow-up"),
  );
  const runtimeRecordsDirectory = normalizeAbsolutePath(
    path.resolve(directiveRoot, "runtime", "records"),
  );
  const runtimePromotionRecordsDirectory = normalizeAbsolutePath(
    path.resolve(directiveRoot, "runtime", "07-promotion-records"),
  );
  const runtimeRegistryDirectory = normalizeAbsolutePath(
    path.resolve(directiveRoot, "runtime", "registry"),
  );

  fs.mkdirSync(runtimeArtifactsDirectory, { recursive: true });
  fs.mkdirSync(runtimeFollowUpDirectory, { recursive: true });
  fs.mkdirSync(runtimeRecordsDirectory, { recursive: true });
  fs.mkdirSync(runtimePromotionRecordsDirectory, { recursive: true });
  fs.mkdirSync(runtimeRegistryDirectory, { recursive: true });
  writeJson(queuePath, createInitialQueue(receivedAt));
  writeJson(exampleSubmissionPath, createExampleSubmission(receivedAt));
  writeJson(exampleRuntimeFollowUpPath, createRuntimeFollowUpExample(receivedAt));
  writeJson(exampleRuntimeRecordPath, createRuntimeRecordExample(receivedAt));
  writeJson(exampleRuntimeProofPath, createRuntimeProofExample(receivedAt));
  writeJson(
    exampleTransformationProofPath,
    createTransformationProofExample(receivedAt),
  );
  writeJson(
    exampleTransformationRecordPath,
    createTransformationRecordExample(receivedAt),
  );
  writeJson(exampleRuntimePromotionPath, createRuntimePromotionExample(receivedAt));
  writeJson(exampleRuntimeRegistryPath, createRuntimeRegistryExample(receivedAt));
  writeJson(configPath, {
    $schema: "https://directive-workspace.dev/schemas/standalone-host-config.schema.json",
    mode: "standalone_reference_api_host",
    directiveRoot: "./directive-root",
    receivedAt,
    server: {
      host: "127.0.0.1",
      port: 8787,
    },
    runtimeArtifacts: {
      relativeRoot: "runtime/standalone-host",
      writeStatusFile: true,
      writeAccessLog: true,
      writeBootLog: true,
    },
    ...(includeSqlitePersistence
      ? {
          persistence: {
            mode: "filesystem_and_sqlite",
          },
        }
      : {}),
    ...(includeAuthTemplate
      ? {
          auth: {
            mode: "none",
          },
        }
      : {}),
  });
  writeText(
    readmePath,
    renderBootstrapReadme({
      hostName,
      outputRoot,
      configFilename,
      receivedAt,
      includeSqlitePersistence,
      includeAuthTemplate,
    }),
  );

  return {
    outputRoot,
    directiveRoot,
    configPath,
    readmePath,
    exampleSubmissionPath,
    exampleRuntimeFollowUpPath,
    exampleRuntimeRecordPath,
    exampleRuntimeProofPath,
    exampleTransformationProofPath,
    exampleTransformationRecordPath,
    exampleRuntimePromotionPath,
    exampleRuntimeRegistryPath,
    createdPaths: [
      configPath,
      readmePath,
      exampleSubmissionPath,
      exampleRuntimeFollowUpPath,
      exampleRuntimeRecordPath,
      exampleRuntimeProofPath,
      exampleTransformationProofPath,
      exampleTransformationRecordPath,
      exampleRuntimePromotionPath,
      exampleRuntimeRegistryPath,
      queuePath,
      runtimeFollowUpDirectory,
      runtimeRecordsDirectory,
      runtimePromotionRecordsDirectory,
      runtimeRegistryDirectory,
      runtimeArtifactsDirectory,
    ],
  };
}

